# Generated by Django 5.1.2 on 2024-10-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='executive',
            new_name='author',
        ),
    ]
